controller_manager:
  ros__parameters:
    update_rate: 100.0
    use_sim_time: true

    joint_state_controller: 
      type: joint_state_controller/JointStateController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    Ti5_controller:
      type: Ti5_arms_controller/Ti5ArmsController


Ti5_controller:
  ros__parameters:
    joint_names:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_R
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_R
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R

    joint_command_interfaces:
      - position
      - velocity
      - effort
    joint_state_interfaces:
      - position
      - velocity
      - effort